// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACLJcYZvNMZf3Q9ZRLPbWreOXoek8TWmI',
    appId: '1:927539981571:web:dbf395129957582d7d4d36',
    messagingSenderId: '927539981571',
    projectId: 'study-app-4c4e7',
    authDomain: 'study-app-4c4e7.firebaseapp.com',
    storageBucket: 'study-app-4c4e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4iF4Qe8GSLT6V5AVSoOlbP3_cScUX5I',
    appId: '1:927539981571:android:334e384e7b9544937d4d36',
    messagingSenderId: '927539981571',
    projectId: 'study-app-4c4e7',
    storageBucket: 'study-app-4c4e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuK4-y-UVQSgrARZPZeCM3OohKmh8Mg7o',
    appId: '1:927539981571:ios:ca4e3a5e7ef6992b7d4d36',
    messagingSenderId: '927539981571',
    projectId: 'study-app-4c4e7',
    storageBucket: 'study-app-4c4e7.appspot.com',
    iosClientId: '927539981571-7u0av5vt2fp2obpko166hqcki8op3usr.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterClassFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuK4-y-UVQSgrARZPZeCM3OohKmh8Mg7o',
    appId: '1:927539981571:ios:ca4e3a5e7ef6992b7d4d36',
    messagingSenderId: '927539981571',
    projectId: 'study-app-4c4e7',
    storageBucket: 'study-app-4c4e7.appspot.com',
    iosClientId: '927539981571-7u0av5vt2fp2obpko166hqcki8op3usr.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterClassFirebase',
  );
}
